
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.3.3-zen1-1-zen - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CsM6oE"
      binary: "/home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CsM6oE"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CsM6oE
        
        Run Build Command(s):/usr/bin/cmake -E env VERBOSE=1 cmake -f Makefile cmTC_62d26/fast && CMake Warning:
          Ignoring extra path from command line:
        
           "cmTC_62d26/fast"
        
        
        CMake Error: Unknown argument -f
        CMake Error: Run 'cmake --help' for all supported options.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/gcc"
    directories:
      source: "/home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yLDF1B"
      binary: "/home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yLDF1B"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: /home/simi/Dev/game-of-life/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yLDF1B
        
        Run Build Command(s):/usr/bin/cmake -E env VERBOSE=1 cmake -f Makefile cmTC_c154f/fast && CMake Warning:
          Ignoring extra path from command line:
        
           "cmTC_c154f/fast"
        
        
        CMake Error: Unknown argument -f
        CMake Error: Run 'cmake --help' for all supported options.
        
      exitCode: 1
...
